version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: notes_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: notesapp
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: notes_user
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - notes_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: notes_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mysql+pymysql://root:password@mysql:3306/notesapp
      - JWT_SECRET_KEY=your-super-secret-key-change-in-production
      - FLASK_ENV=development
    depends_on:
      - mysql
    networks:
      - notes_network
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: notes_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    depends_on:
      - backend
    networks:
      - notes_network
    # volumes:
    #   - ./frontend:/app
    #   - /app/node_modules

volumes:
  mysql_data:

networks:
  notes_network:
    driver: bridge